### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by leesoh** [ncatlabs/pydradis#2]
I'm getting an error when importing pydradis. Here's the steps to reproduce on Windows 10 with Python 3.6.5:

1. pipenv shell --three
2. pip install pydradis
3. python

```
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pydradis import Pydradis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\liams\.virtualenvs\Gradis-TvVwDOpj\lib\site-packages\pydradis\__init__.py", line 1, in <module>
    from pydradis import Pydradis
ImportError: cannot import name 'Pydradis'
```

**Comment by dparker18** [comment]
Can you open a command prompt in C:\Users\liams\.virtualenvs\Gradis-TvVwDOpj\lib\site-packages\pydradis and paste the output of running "dir"? Maybe it's just a windows-specific case sensitivity issue?

**Comment by leesoh** [comment]
Ahh, there it is. the path on windows is `C:\Users\liams\.virtualenvs\Gradis-TvVwDOpj\Lib\site-packages\pydradis`
